// action-types.js

// User Auth
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Driver Auth - OTP
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE';


export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// Business Associate Auth - OTP (Add these new types)
export const SEND_BA_OTP_REQUEST = 'SEND_BA_OTP_REQUEST';
export const SEND_BA_OTP_SUCCESS = 'SEND_BA_OTP_SUCCESS';
export const SEND_BA_OTP_FAILURE = 'SEND_BA_OTP_FAILURE';

export const VERIFY_BA_OTP_REQUEST = 'VERIFY_BA_OTP_REQUEST';
export const VERIFY_BA_OTP_SUCCESS = 'VERIFY_BA_OTP_SUCCESS';
export const VERIFY_BA_OTP_FAILURE = 'VERIFY_BA_OTP_FAILURE';

// Driver Signup
export const DRIVER_SIGNUP_REQUEST = 'DRIVER_SIGNUP_REQUEST';
export const DRIVER_SIGNUP_SUCCESS = 'DRIVER_SIGNUP_SUCCESS';
export const DRIVER_SIGNUP_FAILURE = 'DRIVER_SIGNUP_FAILURE';

export const B_DRIVER_SIGNUP_REQUEST = 'B_DRIVER_SIGNUP_REQUEST';
export const B_DRIVER_SIGNUP_SUCCESS = 'B_DRIVER_SIGNUP_SUCCESS';
export const B_DRIVER_SIGNUP_FAILURE = 'B_DRIVER_SIGNUP_FAILURE';

export const ALL_SERVICES_REQUEST = 'ALL_SERVICES_REQUEST';
export const ALL_SERVICES_SUCCESS = 'ALL_SERVICES_SUCCESS';
export const ALL_SERVICES_FAILURE = 'ALL_SERVICES_FAILURE';

export const SUB_SERVICES_REQUEST = 'SUB_SERVICES_REQUEST';
export const SUB_SERVICES_SUCCESS = 'SUB_SERVICES_SUCCESS';
export const SUB_SERVICES_FAILURE = 'SUB_SERVICES_FAILURE';


export const KYC_DOCUMENT_REQUEST = 'KYC_DOCUMENT_REQUEST';
export const KYC_DOCUMENT_SUCCESS = 'KYC_DOCUMENT_SUCCESS';
export const KYC_DOCUMENT_FAILURE = 'KYC_DOCUMENT_FAILURE';
export const KYC_DOCUMENT_LIST_REQUEST = 'KYC_DOCUMENT_LIST_REQUEST';
export const KYC_DOCUMENT_LIST_SUCCESS = 'KYC_DOCUMENT_LIST_SUCCESS';
export const KYC_DOCUMENT_LIST_FAILURE = 'KYC_DOCUMENT_LIST_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const GET_ONLINE_STATUS_REQUEST = 'GET_ONLINE_STATUS_REQUEST';
export const GET_ONLINE_STATUS_SUCCESS = 'GET_ONLINE_STATUS_SUCCESS';
export const GET_ONLINE_STATUS_FAILURE = 'GET_ONLINE_STATUS_FAILURE';