const EndPoints = {
  authLogin: 'auth/login',
  signup: 'auth/signup',
  driverRegister: '/driver/register',
  sendOtp: 'send-otp',
  pagesByRole: 'pages/by-role',
  verifyOtp: '/verify-otp',
  driverSignup: 'driver/signup',
  allservices: 'allservices',
  allsubservices:"allsubservices",
  businessAssociateSignUp:"ba/register",
   baSendOtp: '/ba/register/otp',
  baRegister: '/ba/register',
  baVerifyLogin: '/ba/verify/login',
  driverkycdocument: '/driver/document_type',
  driverkycdocumentlist: '/getkyc_driver',
  uploadKyc: '/driver/upload-kyc',
  updateProfile: '/driver-profile',
  driverprofile: '/driver-profile-get',
  getOnlineStatus: '/driver/online-status',
  updateOnlineStatus: '/driver/online-update-status',
  baBookings: '/ba/bookings',
  driverBookingHistory: '/driver/getdriverbookinghistory',
  baCreateDriver: '/ba/create/driver',
  baDriverList: '/ba/driverlist',
  baAcceptBooking: '/ba/acceptbooking',
  baAssignDriver: '/ba/assign-driver',
  baCurrentBooking: '/ba/current-booking',
  rechargeWallet: 'driver/recharge',
  rechargeHistory: 'driver/recharge-history',
  driverWithdrawalHistory: 'driver/withdrawal-history',
  driverWithdrawalRequest: 'driver/withdrawal-request',
  getInvoice: '/invoice',
  collectPaymentCompleteRide: '/collect-payment-complete-ride',
  updateLocation: '/driver/update-location',
  // BA self-sharing services
  baServices: '/ba/services',
};
export default EndPoints;
